before:
  hooks:
    - go mod tidy
builds:
  - goos:
      - linux
      - darwin
      - windows
    ignore:
      - goos: linux
        goarch: 386
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: 386
    id: "qf"
    binary: qf
    ldflags:
      - -s -X github.com/ackleymi/examples/version.Version={{.Version}}

archives:
  - name_template: "qf_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - name: qf
    tap:
      owner: ackleymi
      name: homebrew-qf
    homepage: "https://github.com/ackleymi/examples"
    description: "Example QuickFIX/Go Applications."
    install: |
      bin.install "qf"
    caveats: "Thanks for installing the Quickfix/Go examples"
    plist: |
      <?xml version="1.0" encoding="UTF-8"?>
      <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
      <plist version="1.0">
        <dict>
          <key>KeepAlive</key>
          <dict>
            <key>SuccessfulExit</key>
            <false/>
          </dict>
          <key>Label</key>
          <string>#{plist_name}</string>
          <key>RunAtLoad</key>
          <true/>
          <key>WorkingDirectory</key>
          <string>#{var}</string>
          <key>StandardErrorPath</key>
          <string>#{var}/log/qtrn.log</string>
          <key>StandardOutPath</key>
          <string>#{var}/log/qtrn.log</string>
        </dict>
      </plist>

snapcrafts:
  - name_template: "qf_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    name: quickfixgo-qf
    publish: true
    summary: Example QuickFIX/Go Applications.
    description: Example QuickFIX/Go Applications.
    grade: stable
    confinement: strict
    layout:
      /etc/qf:
        bind: $SNAP_DATA/etc
scoop:
    name: qf
    bucket:
      owner: ackleymi
      name: scoop-qf
    commit_msg_template: "Scoop manifest update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: https://github.com/ackleymi/examples
    description: Example QuickFIX/Go Applications.
    post_install: ["Write-Host 'Thanks for installing the Quickfix/Go examples'"]